<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="FluentAssertions" />
    <Using Include="Fileway.Shared.Processors" />
    <Using Include="Fileway.Shared.Formats" />
    <Using Include="Fileway.Shared.Errors" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Fileway.Client\Fileway.Client.csproj" />
    <ProjectReference Include="..\..\src\Fileway.Shared\Fileway.Shared.csproj" />
  </ItemGroup>

</Project>
